name: deploy-book
on:
  push:
    branches:
      - main        # O la rama que uses
  workflow_dispatch:  # Permite deploy manual desde la UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Jupyter Book
        run: pip install jupyter-book

      - name: Build the book
        run: jupyter-book build .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
